# SPDX-License-Identifier: Apache-2.0

load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_verilator//verilator:defs.bzl", "verilator_cc_library")
load("@rules_verilog//verilog:defs.bzl", "verilog_library")

# bazel run //:buildifier
buildifier(
    name = "buildifier",
)

verilog_library(
    name = "counter",
    srcs = ["counter.v"],
    top_module = "counter",
)

# Verilates the design into a C++ model that the test below drives.
verilator_cc_library(
    name = "counter_verilator",
    module = ":counter",
)

cc_test(
    name = "counter_test",
    size = "small",
    srcs = ["counter_test.cc"],
    deps = [
        ":counter_verilator",
        "@googletest//:gtest_main",
    ],
)
